name: Feature Request
description: Suggest an idea for VIES Query
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New command-line option/flag
        - New output format
        - New VAT validation feature
        - Performance improvement
        - Documentation enhancement
        - Developer experience improvement
        - Integration/API feature
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "I've also considered..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        - I need this feature because...
        - This would help me...
        - Current workflow: ...
        - Desired workflow: ...
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: If applicable, show how you would use this feature
      placeholder: |
        # Example command:
        viesquery --new-feature DE123456789
        
        # Expected output:
        [Show expected output here]
      render: shell

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would be helpful)
        - High (important for my workflow)
        - Critical (blocking my use case)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change)
        - Medium (moderate effort)
        - Complex (significant effort)
        - Not sure

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        - Links to relevant documentation
        - Screenshots or mockups
        - Related issues or discussions
        - External tools that have this feature

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you interested in contributing?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to provide feedback during development

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: This feature request is specific and actionable
          required: true
        - label: I have provided sufficient detail for the maintainers to understand the request
          required: true
